### ISSUE TITLE
Add PNG output option to graphs [Feature request]

### ISSUE THREAD

**Issue by shayanb** [ConsenSys/vscode-solidity-auditor#36]
When generating the graph of a contract, the output options are SVG, and DOT. Having the option to generate a common format such as PNG is useful too.

**Comment by tintinweb** [comment]
Heya @shayanb,

I avoided adding this because converting vector to a raster graphics poses the problem that depending on how large the graph is we might end up rendering a png that is too low in resolution to be readable or too high in resolution for the information in the graph.

Let's keep this one up for discussion and see if there are more people requesting this 🙌

**Comment by tintinweb** [comment]
let's close this unless we really need it :)
