### ISSUE TITLE
Function selector is incorrect if there's a comment in the function signature definition

### ISSUE THREAD

**Issue by mds1** [ConsenSys/vscode-solidity-auditor#68]
Steps to reproduce:
1. See this [function](https://github.com/ScopeLift/umbra-protocol/blob/fa2e17367d66a85f20c77299ded5942d9ab64fe0/contracts/contracts/Umbra.sol#L145-L151) has an inline comment
2. Run "List function signatures" for this file
3. Notice how it outputs `1137c1f8  =>  sendToken(address,address,uint256,bytes32,//)` when it should output `b9bfabe1 => sendToken(address,address,uint256,bytes32,bytes32)`

Function linked above:

```solidity
function sendToken(
    address _receiver,
    address _tokenAddr,
    uint256 _amount,
    bytes32 _pkx, // ephemeral public key x coordinate
    bytes32 _ciphertext
) external payable {
   ...
}
```

**Comment by tintinweb** [comment]
@mds1,

fixed it for the upcoming v0.1.1. let me know if you need it earlier and I can probably provide you an alpha.

the function signature extraction is super hacky and I do not expect that a lot of people are using it. if it turns out it is actually being used I might refactor the lexical extraction and actually use the AST.


cheers
